import type { Metadata } from 'next';
import '../globals.css';
import { SanityLive } from '@/sanity/lib/live';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Fungi Finders',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      {children}
      <SanityLive />
      <Footer />
    </main>
  );
}
